create or alter procedure sp_oltp_viagem(@data_carga datetime)
as
begin
	DELETE FROM TB_AUX_VIAGEM
	WHERE @data_carga = DATA_CARGA

	DECLARE @DATA_VIAGEM DATETIME,--
			@ID_PROCESSO_VIAGEM INT,
			@COD_ORGAO_SUPERIOR INT,--
			@CPF INT,--
			@CIDADE_ORIGEM VARCHAR(100),--
			@CIDADE_DESTINO VARCHAR(100),--
			@CIDADE_ORIGEM1 VARCHAR(100),--
			@CIDADE_DESTINO1 VARCHAR(100),--
			@TIPO VARCHAR(15),--
			@COD_ENTIDADE_VINCULADA INT,--
			@CARGO VARCHAR(255),--
			@VALOR_PASSAGEM NUMERIC(10,2),--
			@VALOR_DIARIA NUMERIC(10,2),--
			@VALOR_OUTROS NUMERIC(10,2),--
			@VALOR_TOTAL NUMERIC(10,2)--

	DECLARE CUR CURSOR FOR
	SELECT ID_PROCESSO_VIAGEM, CPF, CARGO, VALOR_OUTROS FROM TB_VIAGENS

	OPEN CUR
	FETCH CUR INTO @ID_PROCESSO_VIAGEM, @CPF, @CARGO, @VALOR_OUTROS

	WHILE @@FETCH_STATUS = 0
	BEGIN
		SELECT @DATA_VIAGEM = DT_ORIGEM FROM TB_TRECHO 
		WHERE ID_PROCESSO_VIAGEM = @ID_PROCESSO_VIAGEM AND
			  SEQUENCIA_VIAGEM = 1

		SELECT TOP 1 @COD_ORGAO_SUPERIOR = COD_ORGAO_SUPERIOR, @COD_ENTIDADE_VINCULADA = COD_ORGAO_PAGADOR 
		FROM TB_PAGAMENTO 
		WHERE ID_PROCESSO_VIAGEM = @ID_PROCESSO_VIAGEM

		SELECT @VALOR_DIARIA = SUM(VALOR) FROM TB_PAGAMENTO 
		WHERE ID_PROCESSO_VIAGEM = @ID_PROCESSO_VIAGEM AND
			  TIPO = 'DIÁRIAS'

		IF (SELECT PAIS_ORIGEM_VOLTA FROM TB_PASSAGEM WHERE ID_PROCESSO_VIAGEM = @ID_PROCESSO_VIAGEM) != 'Sem informação'
		BEGIN
			SELECT @VALOR_PASSAGEM = (VALOR_PASSAGEM + VALOR_TAXA_SERVICO), @CIDADE_ORIGEM = CIDADE_ORIGEM_IDA, @CIDADE_DESTINO = CIDADE_DESTINO_IDA, @TIPO = TIPO_PASSAGEM, @CIDADE_ORIGEM1 = CIDADE_ORIGEM_VOLTA, @CIDADE_DESTINO1 = CIDADE_DESTINO_VOLTA
			FROM TB_PASSAGEM 
			WHERE ID_PROCESSO_VIAGEM = @ID_PROCESSO_VIAGEM

			SET @VALOR_PASSAGEM = @VALOR_PASSAGEM /2

			SET @VALOR_TOTAL = @VALOR_DIARIA + @VALOR_OUTROS + @VALOR_PASSAGEM

			INSERT INTO TB_AUX_VIAGEM VALUES
			(@data_carga, @DATA_VIAGEM, @ID_PROCESSO_VIAGEM, @COD_ORGAO_SUPERIOR, @CPF, @CIDADE_ORIGEM, @CIDADE_DESTINO, @TIPO, @COD_ENTIDADE_VINCULADA, @CARGO, @VALOR_PASSAGEM, @VALOR_DIARIA, @VALOR_OUTROS, @VALOR_TOTAL)

			INSERT INTO TB_AUX_VIAGEM VALUES
			(@data_carga, @DATA_VIAGEM, @ID_PROCESSO_VIAGEM, @COD_ORGAO_SUPERIOR, @CPF, @CIDADE_ORIGEM1, @CIDADE_DESTINO1, @TIPO, @COD_ENTIDADE_VINCULADA, @CARGO, @VALOR_PASSAGEM, @VALOR_DIARIA, @VALOR_OUTROS, @VALOR_TOTAL)

		END
		ELSE
		BEGIN
			DECLARE CUR_PASS CURSOR FOR
			SELECT (VALOR_PASSAGEM + VALOR_TAXA_SERVICO), CIDADE_ORIGEM_IDA, CIDADE_DESTINO_IDA
			FROM TB_PASSAGEM
			WHERE ID_PROCESSO_VIAGEM = @ID_PROCESSO_VIAGEM

			OPEN CUR_PASS
			FETCH CUR_PASS INTO @VALOR_PASSAGEM, @CIDADE_ORIGEM, @CIDADE_DESTINO

			WHILE @@FETCH_STATUS = 0
			BEGIN
				SET @VALOR_TOTAL = @VALOR_DIARIA + @VALOR_OUTROS + @VALOR_PASSAGEM

				INSERT INTO TB_AUX_VIAGEM VALUES
				(@data_carga, @DATA_VIAGEM, @ID_PROCESSO_VIAGEM, @COD_ORGAO_SUPERIOR, @CPF, @CIDADE_ORIGEM, @CIDADE_DESTINO, @TIPO, @COD_ENTIDADE_VINCULADA, @CARGO, @VALOR_PASSAGEM, @VALOR_DIARIA, @VALOR_OUTROS, @VALOR_TOTAL)

				FETCH CUR_PASS INTO @VALOR_PASSAGEM, @CIDADE_ORIGEM, @CIDADE_DESTINO
			END

			CLOSE CUR_PASS
			DEALLOCATE CUR_PASS
		END

		FETCH CUR INTO @ID_PROCESSO_VIAGEM, @CPF, @CARGO, @VALOR_OUTROS

	END
	CLOSE CUR
	DEALLOCATE CUR
end