create or alter procedure sp_oltp_trajeto(@data_carga datetime)
as
begin
	DELETE FROM TB_AUX_TRAJETO
	WHERE @data_carga = DATA_CARGA

	INSERT INTO TB_AUX_TRAJETO
	SELECT @data_carga, UF_ORIGEM_IDA, CIDADE_ORIGEM_IDA, UF_DESTINO_IDA, CIDADE_DESTINO_IDA
	FROM TB_PASSAGEM

	INSERT INTO TB_AUX_TRAJETO
	SELECT @data_carga, UF_ORIGEM_VOLTA, CIDADE_ORIGEM_VOLTA, UF_DESTINO_VOLTA, CIDADE_DESTINO_VOLTA
	FROM TB_PASSAGEM
	WHERE PAIS_ORIGEM_VOLTA != 'Sem informação'
end

EXEC sp_oltp_trajeto '20240324'

SELECT * FROM TB_AUX_TRAJETO