CREATE OR ALTER PROCEDURE sp_dim_pessoa(@data_carga DATETIME)
AS
BEGIN
    DECLARE @CPF VARCHAR (14)
    DECLARE @NOME VARCHAR(100)

    DECLARE CUR CURSOR FOR
    SELECT CPF,NOME FROM TB_AUX_PESSOA WHERE DATA_CARGA=@data_carga;

    OPEN CUR 
    FETCH NEXT FROM CUR INTO @CPF,@NOME

    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF @NOME != 'Informações protegidas por sigilo' AND NOT EXISTS (SELECT * FROM DIM_PESSOA WHERE CPF=@CPF AND NOME=@NOME)
        BEGIN
            INSERT INTO DIM_PESSOA (CPF,NOME)
            VALUES (@CPF,@NOME)
        END
        FETCH NEXT FROM CUR INTO @CPF,@NOME
    END

    CLOSE CUR;
    DEALLOCATE CUR;
END

-- Teste
DELETE FROM DIM_PESSOA
exec sp_dim_pessoa '20240324'

select * from DIM_PESSOA