CREATE OR ALTER PROCEDURE sp_dim_pessoa(@data_carga DATETIME)
AS
BEGIN
    DECLARE @CPF INT
    DECLARE @NOME VARCHAR(100)

    DECLARE CUR CURSOR FOR
    SELECT CPF,NOME FROM TB_AUX_PESSOA WHERE DATA_CARGA=@data_carga;

    OPEN CUR 
    FETCH NEXT FROM CUR INTO @CPF,@NOME

    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF NOT EXISTS (SELECT * FROM DIM_PESSOA WHERE CPF=@CPF)
        BEGIN
            INSERT INTO DIM_PESSOA (CPF,NOME)
            VALUES (@CPF,@NOME)
        END
        ELSE
        BEGIN
            UPDATE DIM_PESSOA SET CPF = @CPF,NOME = @NOME WHERE CPF = @CPF
        END 
        FETCH NEXT FROM CUR INTO @CPF,@NOME
    END

    CLOSE CUR;
    DEALLOCATE CUR;
END

-- Teste

exec sp_dim_pessoa '20230321'

select * from DIM_PESSOA