CREATE OR ALTER PROCEDURE sp_dim_trajeto(@data_carga DATETIME)
AS
BEGIN
    DECLARE @UF_ORIGEM VARCHAR(50)
	DECLARE @CIDADE_ORIGEM VARCHAR(100)
	DECLARE @UF_DESTINO VARCHAR(50) 
	DECLARE @CIDADE_DESTINO VARCHAR(100)

    DECLARE CUR CURSOR FOR
    SELECT UF_ORIGEM,CIDADE_ORIGEM,UF_DESTINO,CIDADE_DESTINO FROM TB_AUX_TRAJETO WHERE DATA_CARGA=@data_carga;

    OPEN CUR 
    FETCH NEXT FROM CUR INTO @UF_ORIGEM,@CIDADE_ORIGEM,@UF_DESTINO,@CIDADE_DESTINO

    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF NOT EXISTS (SELECT * FROM DIM_TRAJETO WHERE CIDADE_ORIGEM=@CIDADE_ORIGEM AND CIDADE_DESTINO=@CIDADE_DESTINO)
        BEGIN
            INSERT INTO DIM_TRAJETO (UF_ORIGEM,CIDADE_ORIGEM,UF_DESTINO,CIDADE_DESTINO)
            VALUES (@UF_ORIGEM,@CIDADE_ORIGEM,@UF_DESTINO,@CIDADE_DESTINO)
        END
        FETCH NEXT FROM CUR INTO @UF_ORIGEM,@CIDADE_ORIGEM,@UF_DESTINO,@CIDADE_DESTINO

    END

    CLOSE CUR;
    DEALLOCATE CUR;
END

-- Teste

exec sp_dim_trajeto '20240324'

select * from DIM_TRAJETO where CIDADE_ORIGEM = 'Salvador'