CREATE OR ALTER PROCEDURE sp_dim_entidade_vinculada(@data_carga DATETIME)
AS
BEGIN
    DECLARE @COD_ENTIDADE INT,
			@NOME VARCHAR(100),
			@CURRENT_NOME VARCHAR(100)

    DECLARE CUR CURSOR FOR
    SELECT COD_ENTIDADE_VINCULADA, NOME 
	FROM TB_AUX_ENTIDADE_VINCULADA 
	WHERE DATA_CARGA = @data_carga;

    OPEN CUR 
    FETCH NEXT FROM CUR INTO @COD_ENTIDADE, @NOME

    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF EXISTS (SELECT 1 FROM DIM_ENTIDADE_VINCULADA WHERE COD_ENTIDADE_VINCULADA = @COD_ENTIDADE)
        BEGIN
            SELECT @CURRENT_NOME = NOME
			FROM DIM_ENTIDADE_VINCULADA
			WHERE COD_ENTIDADE_VINCULADA = @COD_ENTIDADE

			IF @CURRENT_NOME != @NOME
			BEGIN
				UPDATE DIM_ENTIDADE_VINCULADA
				SET NOME = @NOME
				WHERE COD_ENTIDADE_VINCULADA = @COD_ENTIDADE
			END
        END
		ELSE
		BEGIN
			INSERT INTO DIM_ENTIDADE_VINCULADA (COD_ENTIDADE_VINCULADA,NOME)
            VALUES (@COD_ENTIDADE,@NOME)
		END
        FETCH NEXT FROM CUR INTO @COD_ENTIDADE,@NOME
    END

    CLOSE CUR;
    DEALLOCATE CUR;
END

-- Teste

exec sp_dim_entidade_vinculada '20240324'

select * from DIM_ENTIDADE_VINCULADA