create or alter procedure sp_fato_viagem(@data_carga datetime)
as
begin
    DECLARE @ID_PROCESSO_VIAGEM INT,
			@AUX_DATA_VIAGEM dateTIME,
			@AUX_COD_ORGAO_SUPERIOR INT,
			@AUX_CIDADE_ORIGEM VARCHAR(100),
			@AUX_CIDADE_DESTINO VARCHAR(100),
			@AUX_TIPO VARCHAR(15),
			@AUX_CARGO VARCHAR(255),
			@AUX_COD_ENTIDADE_VINCULADA INT,
			@AUX_CPF VARCHAR(14),
			@VALOR_PASSAGEM NUMERIC(10,2),
			@VALOR_DIARIA NUMERIC(10,2),
			@VALOR_OUTROS NUMERIC(10,2),
			@VALOR_TOTAL NUMERIC(10,2),
			
			@ID_DATA_VIAGEM INT,
			@ID_ORGAO_SUPERIOR INT,
			@ID_TRAJETO INT,
			@ID_TIPO INT,
			@ID_CARGO INT,
			@ID_ENTIDADE_VINCULADA INT,
			@ID_PESSOA INT,
			@ID_LOCALIDADE INT,

			@VIOLACAO VARCHAR(150)

			

    DECLARE CUR CURSOR FOR
    SELECT DATA_VIAGEM,	ID_PROCESSO_VIAGEM,	COD_ORGAO_SUPERIOR,	CPF, CIDADE_ORIGEM,	CIDADE_DESTINO,	TIPO, COD_ENTIDADE_VINCULADA, CARGO, VALOR_PASSAGEM, VALOR_DIARIA, VALOR_OUTROS, VALOR_TOTAL 
	FROM TB_AUX_VIAGEM 
	WHERE DATA_CARGA = @DATA_CARGA

    OPEN CUR 
    FETCH NEXT FROM CUR INTO @AUX_DATA_VIAGEM, @ID_PROCESSO_VIAGEM,	@AUX_COD_ORGAO_SUPERIOR, @AUX_CPF, @AUX_CIDADE_ORIGEM, @AUX_CIDADE_DESTINO, @AUX_TIPO, @AUX_COD_ENTIDADE_VINCULADA, @AUX_CARGO, @VALOR_PASSAGEM, @VALOR_DIARIA, @VALOR_OUTROS, @VALOR_TOTAL 
    
	WHILE @@FETCH_STATUS = 0
    BEGIN
		SET @ID_DATA_VIAGEM = NULL
		SET @ID_ORGAO_SUPERIOR = NULL
		SET @ID_PESSOA = NULL
		SET @ID_TRAJETO = NULL
		SET @ID_TIPO = NULL
		SET @ID_CARGO = NULL
		SET @ID_ENTIDADE_VINCULADA = NULL
		SET @ID_LOCALIDADE = NULL

		SELECT @ID_DATA_VIAGEM = ID_TEMPO 
		FROM DIM_TEMPO 
		WHERE DATA = @AUX_DATA_VIAGEM

		SELECT @ID_ORGAO_SUPERIOR = ID 
		FROM DIM_ORGAO_SUPERIOR 
		WHERE COD_ORGAO_SUPERIOR = @AUX_COD_ORGAO_SUPERIOR

		SELECT @ID_PESSOA = ID 
		FROM DIM_PESSOA 
		WHERE CPF = @AUX_CPF

		SELECT @ID_TRAJETO =ID 
		FROM DIM_TRAJETO 
		WHERE CIDADE_ORIGEM = @AUX_CIDADE_ORIGEM AND CIDADE_DESTINO = @AUX_CIDADE_DESTINO

		SELECT @ID_TIPO = ID 
		FROM DIM_TIPO 
		WHERE NOME = @AUX_TIPO

		SELECT @ID_CARGO = ID 
		FROM DIM_CARGO 
		WHERE NOME = @AUX_CARGO

		SELECT @ID_ENTIDADE_VINCULADA = ID 
		FROM DIM_ENTIDADE_VINCULADA 
		WHERE COD_ENTIDADE_VINCULADA = @AUX_COD_ENTIDADE_VINCULADA

		SELECT @ID_LOCALIDADE = ID
		FROM DIM_LOCALIDADE 
		WHERE CIDADE = @AUX_CIDADE_ORIGEM

		IF @ID_DATA_VIAGEM IS NULL
		BEGIN
			SET @VIOLACAO = 'DATA DA VIAGEM INVALIDA'
		END
		ELSE
		BEGIN
			IF @ID_ORGAO_SUPERIOR IS NULL
			BEGIN
				SET @VIOLACAO = 'CODIGO DO ORGAO SUPERIOR INVALIDO'
			END
			ELSE
			BEGIN
				IF @ID_PESSOA IS NULL
				BEGIN
					SET @VIOLACAO = 'CODIGO DA PESSOA INVALIDO'
				END
				ELSE
				BEGIN
					IF @ID_TRAJETO IS NULL
					BEGIN
						SET @VIOLACAO = 'CODIGO DO TRAJETO INVALIDO'
					END
					ELSE
					BEGIN
						IF @ID_TIPO IS NULL
						BEGIN
							SET @VIOLACAO = 'CODIGO DO TIPO DA VIAGEM INVALIDO'
						END
						ELSE
						BEGIN
							IF @ID_CARGO IS NULL
							BEGIN
								SET @VIOLACAO = 'CODIGO DO CARGO INVALIDO'
							END
							ELSE
							BEGIN
								IF @ID_ENTIDADE_VINCULADA IS NULL
								BEGIN
									SET @VIOLACAO = 'CODIGO DA ENTIDADE VINCULADA INVALIDO'
								END
								ELSE
								BEGIN
									IF @ID_LOCALIDADE IS NULL
									BEGIN
										SET @VIOLACAO = 'CODIGO DA LOCALIDADE INVALIDO'
									END
								END
							END
						END
					END
				END
			END
		END

		IF @VIOLACAO IS NOT NULL
		BEGIN
			INSERT INTO TB_VIO_VIAGEM
			VALUES (@data_carga, @AUX_DATA_VIAGEM, @ID_PROCESSO_VIAGEM,	@AUX_COD_ORGAO_SUPERIOR, @AUX_CPF, @AUX_CIDADE_ORIGEM, @AUX_CIDADE_DESTINO, @AUX_TIPO, @AUX_COD_ENTIDADE_VINCULADA, @AUX_CARGO, @VALOR_PASSAGEM, @VALOR_DIARIA, @VALOR_OUTROS, @VALOR_TOTAL, GETDATE(), @VIOLACAO)
		END
		ELSE
		BEGIN
			INSERT INTO FATO_VIAGEM (ID_DATA_VIAGEM, ID_PROCESSO_VIAGEM, ID_ORGAO_SUPERIOR, ID_TRAJETO, ID_TIPO, ID_CARGO, ID_ENTIDADE_VINCULADA, ID_PESSOA, ID_LOCALIDADE,	QUANTIDADE,	VALOR_PASSAGEM, VALOR_DIARIA, VALOR_OUTROS, VALOR_TOTAL)
			VALUES (@ID_DATA_VIAGEM, @ID_PROCESSO_VIAGEM, @ID_ORGAO_SUPERIOR, @ID_TRAJETO, @ID_TIPO, @ID_CARGO, @ID_ENTIDADE_VINCULADA, @ID_PESSOA, @ID_LOCALIDADE, 1, @VALOR_PASSAGEM, @VALOR_DIARIA, @VALOR_OUTROS, @VALOR_TOTAL)
		END

		FETCH NEXT FROM CUR INTO @AUX_DATA_VIAGEM, @ID_PROCESSO_VIAGEM,	@AUX_COD_ORGAO_SUPERIOR, @AUX_CPF, @AUX_CIDADE_ORIGEM, @AUX_CIDADE_DESTINO, @AUX_TIPO, @AUX_COD_ENTIDADE_VINCULADA, @AUX_CARGO, @VALOR_PASSAGEM, @VALOR_DIARIA, @VALOR_OUTROS, @VALOR_TOTAL 

    END
    CLOSE CUR
    DEALLOCATE CUR
end

-- Teste

exec sp_fato_viagem '20240324'

SELECT * FROM FATO_VIAGEM