CREATE TABLE DIM_ORGAO_SUPERIOR (
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	COD_ORGAO_SUPERIOR INT NULL,
	NOME VARCHAR(100) NULL
)

CREATE TABLE DIM_PESSOA (
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	CPF VARCHAR(14) NULL,
	NOME VARCHAR(255) NULL
)

CREATE TABLE DIM_TRAJETO (
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	UF_ORIGEM VARCHAR(50) NULL,
	CIDADE_ORIGEM VARCHAR(100) NULL,
	UF_DESTINO VARCHAR(50) NULL,
	CIDADE_DESTINO VARCHAR(100) NULL,
)
CREATE TABLE DIM_LOCALIDADE(
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	UF VARCHAR(50) NULL,	
	CIDADE VARCHAR(100) NULL,
)

CREATE TABLE DIM_TIPO (
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	NOME VARCHAR(15) NULL
)

CREATE TABLE DIM_CARGO (
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	NOME VARCHAR(255) NULL
)

CREATE TABLE DIM_ENTIDADE_VINCULADA (
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	COD_ENTIDADE_VINCULADA INT NULL,
	NOME VARCHAR(100) NULL
)

CREATE TABLE DIM_TEMPO (
	ID_TEMPO BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NIVEL VARCHAR(8) NOT NULL CHECK (NIVEL IN ('DIA','MES','ANO')),
	DATA DATETIME NULL,
	DIA INT NULL,
	DIA_SEMANA VARCHAR(50) NULL,
	FIM_SEMANA VARCHAR(3) NULL CHECK (FIM_SEMANA IN ('SIM','NAO')),
	FERIADO VARCHAR(100) NULL,
	FL_FERIADO VARCHAR(3) NULL CHECK (FL_FERIADO IN ('SIM','NAO')),
	MES INT NULL,
	NOME_MES VARCHAR(100) NULL,
	TRIMESTRE INT NULL,
	NOME_TRIMESTRE VARCHAR(100) NULL,
	SEMESTRE INT NULL,
	NOME_SEMESTRE VARCHAR(100) NULL,
	ANO INT NOT NULL
)

CREATE TABLE FATO_VIAGEM(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ID_DATA_VIAGEM INT NULL,
	ID_PROCESSO_VIAGEM INT NULL,
	ID_ORGAO_SUPERIOR INT REFERENCES DIM_ORGAO_SUPERIOR(ID),
	ID_TRAJETO INT REFERENCES DIM_TRAJETO(ID),
	ID_TIPO INT REFERENCES DIM_TIPO(ID),
	ID_CARGO INT REFERENCES DIM_CARGO(ID),
	ID_ENTIDADE_VINCULADA INT REFERENCES DIM_ENTIDADE_VINCULADA(ID),
	ID_PESSOA INT REFERENCES DIM_PESSOA(ID),
	ID_LOCALIDADE INT REFERENCES DIM_LOCALIDADE(ID),
	QUANTIDADE INT NOT NULL DEFAULT (1),
	VALOR_PASSAGEM NUMERIC(10,2) NULL,
	VALOR_DIARIA NUMERIC(10,2) NULL,
	VALOR_OUTROS NUMERIC(10,2) NULL,
	VALOR_TOTAL NUMERIC(10,2) NULL
)