-- Tabelas de Violações

CREATE TABLE TB_VIO_VIAGEM (
    ID_VIOLACAO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DATA_CARGA DATETIME NOT NULL,
    DATA_VIAGEM DATETIME NULL,
    ID_PROCESSO_VIAGEM INT NULL,
    COD_ORGAO_SUPERIOR INT NULL,
    CPF VARCHAR(20) NULL,
    CIDADE_ORIGEM VARCHAR(100) NULL,
    CIDADE_DESTINO VARCHAR(100) NULL,
    TIPO VARCHAR(15) NULL,
    COD_ENTIDADE_VINCULADA INT NULL,
    CARGO VARCHAR(255) NULL,
    VALOR_PASSAGEM NUMERIC(10,2) NULL,
    VALOR_DIARIA NUMERIC(10,2) NULL,
	VALOR_OUTROS NUMERIC(10,2) NULL,
    VALOR_TOTAL NUMERIC(10,2) NULL,
	DT_ERRO DATETIME NOT NULL,
    VIOLACAO VARCHAR(150) NOT NULL
)